# ---------- Stage 1: Build ----------
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o car_inventory .

# ---------- Stage 2: Runtime ----------
FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/car_inventory .
EXPOSE 3051
ENTRYPOINT ["./car_inventory"]
